# Generated by Django 2.0.5 on 2018-05-18 11:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(default='', max_length=10, verbose_name='都道府県名')),
                ('n03_002', models.CharField(blank=True, default='', max_length=20, verbose_name='支庁・振興局名')),
                ('n03_003', models.CharField(blank=True, default='', max_length=20, verbose_name='郡・政令都市名')),
                ('n03_004', models.CharField(blank=True, default='', max_length=20, verbose_name='市区町村名')),
                ('n03_007', models.CharField(blank=True, default='', max_length=5, verbose_name='行政区域コード')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=6668)),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域一覧',
            },
        ),
    ]
